
name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Configure
      run: |
        sudo apt-get update
        sudo apt-get install -y -f \
        libgtk-3-dev \
        libwebkit2gtk-4.0-37 \
        libwebkit2gtk-4.0-dev \
        libappindicator3-dev
    - name: Build
      run: bash build_linux.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux_binary
        path: bin/neutralino-linux_x64

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      run: ./build_windows.bat
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win_binary
        path: bin/neutralino-win_x64.exe

  build-darwin:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: bash build_macos.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: darwin_binary
        path: bin/neutralino-mac_x64
        
  create-release:
    needs: [build-linux, build-windows, build-darwin]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Clean previous binaries
      run: |
        rm -f \
        ./bin/neutralino-linux_x64 \
        ./bin/neutralino-win_x64.exe \
        ./bin/neutralino-mac_x64
        
    - name: Download Linux build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: linux_binary
        path: ./bin/neutralino-linux_x64
        
    - name: Download Windows build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: win_binary
        path: ./bin/neutralino-win_x64.exe
        
    - name: Download Darwin build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: darwin_binary
        path: ./bin/neutralino-mac_x64
